### PR TITLE
updating port in a log message

### PR DESCRIPTION
**Pull request by ighouri**

### CODE REVIEW

**Comment by mosabua** [comment]
Should we add .. "on the host machine" or something?

**Comment by mosabua** [comment]
Otherwise totally +1

**Comment by ighouri** [comment]
Sure @mosabua you can update the message

**Comment by ighouri** [comment]
@mosabua updated the message

**Comment by mosabua** [comment]
Great.

**Comment by ighouri** [comment]
closing this as these changes already done in another PR.

**Pull request closed without merging**
